const express=require("express");
const URL=require("../models/url")
const router=express.Router();

// This functn is to get urls generated by a particular user
router.get("/",async (req,res)=>{
    if(!req.user) return res.redirect("/login");    // req.user (user in middleware folder);
    const allurls=await URL.find({craetedBy:req.user._id});
    return res.render("home",{
        urls:allurls,           // we should use the same variable that is (urls) in the home-page of views folder
    })
});

router.get("/signup",(req,res)=>{
    return res.render("signup");
});

router.get("/login",(req,res)=>{
    return res.render("login");
});


module.exports=router;